### ISSUE TITLE
Problem on Typespecs with the arrow operator

### ISSUE THREAD

**Issue by lud-wj** [marcandre/freedom_formatter#10]
The formatter is transforming this:

```elixir
@spec reduce_ok(Enumerable.t(), term, (term, term -> result)) :: result
```

into this:

```elixir
@spec reduce_ok(Enumerable.t(), term, [->(term, term, result)]) :: result
```

Which is invalid. I have the `trailing_comma: true` option.

**Comment by s3cur3** [comment]
I believe this is specific to Elixir 1.17 (at least that's when I started noticing it).

**Comment by marcandre** [comment]
Released v2.1.1
Thanks, and sorry again for the delay

**Comment by s3cur3** [comment]
Thanks so much, Marc-André! 💜

**Comment by lud-wj** [comment]
Thank you!
