### ISSUE TITLE
Problem with nonempty list typespecs

### ISSUE THREAD

**Issue by s3cur3** [marcandre/freedom_formatter#11]
Hi there! Thanks for the great library. We've used it happily at Felt for a couple years now. ☺️

I'm running into an issue with Elixir 1.17, where I have a typespec like this:

```elixir
@spec join([String.t(), ...]) :: String.t()
```

With the `trailing_comma: true` and `local_pipe_with_parens: true` settings, it gets reformatted to:

```elixir
@spec join([String.t(), ...()]) :: String.t()
```

(Note the new `()` following the `...`)

This breaks compilation.

**Comment by axelson** [comment]
@marcandre ping! This is currently holding up upgrading to Elixir 1.17 for us.

**Comment by marcandre** [comment]
Oh, sorry, I missed the notification and completely forgot to make recent releases, sorry.
Let me make an updated release ASAP

**Comment by marcandre** [comment]
Released v2.1.1
Thanks, and sorry again for the delay

**Comment by s3cur3** [comment]
Thank you, Marc-André! 💜

**Comment by axelson** [comment]
Thank you! And wow that was fast!

**Comment by marcandre** [comment]
I'll try to make releases at every minor release of Elixir, but don't hesitate to send requests if I don't and/or ping if I don't answer within a few days.
